### ISSUE TITLE
[BUG] Résolution + Animalisme

### ISSUE THREAD

**Issue by Gabryel666** [Rayji96/foundry-V5#104]
Hello, i report a bug on a roll.

When I roll Resolution + Animalism there are 5 dices rolling when I should only have 2.

![image](https://user-images.githubusercontent.com/65908230/127369796-11d00a4f-09bb-4b30-b9db-5e48374baab9.png)

![image](https://user-images.githubusercontent.com/65908230/127369852-ec430411-127a-45ac-b4f9-6ce709b28143.png)

![image](https://user-images.githubusercontent.com/65908230/127369946-7fc41a73-5775-4490-8cc0-643f3895e867.png)

Module : Dice so Nice

**Comment by Rayji96** [comment]
What is your Blood Potency set to?

**Comment by Rayji96** [comment]
@Gabryel666 The latest update now automatically adds your blood potency bonus to power rolls

**Comment by Gabryel666** [comment]
Hi. So sorry !! In fact, it's the blood potency !
No bug in fact :)
Thx
