### ISSUE TITLE
Error in German translation

### ISSUE THREAD

**Issue by KaiderWeise** [Rayji96/foundry-V5#106]
![Vampire Fähigkeiten](https://user-images.githubusercontent.com/78543670/128625403-04ce5f46-3e33-4c65-a559-704f5e865076.PNG)
**Describe the bug**
In the German version of the character sheet, the ability Intimidate appears twice. The marked ability **Einschüchtern** should read: **Ausflüchte**. In English, this is Subterfuge. The correct Intimidate is correctly five lines above. Unfortunately, I don't know how to fix this myself, so I'm reporting it here. 

**Desktop (please complete the following information):**
- FoundryVTT Version [e.g. 22]: 0.8.8
- Foundry-V5 Version [e.g. 22]: 1.6.2

**Comment by Rayji96** [comment]
Fixed in linked PR
