### ISSUE TITLE
[FEATURE] New chat dices design

### ISSUE THREAD

**Issue by Gabryel666** [Rayji96/foundry-V5#108]
I modified the logos to make the results of the dice rolls nicer (In my opinion). Here is the result.

![logos](https://user-images.githubusercontent.com/65908230/131214384-841b2a63-10a4-4773-bffb-a86e5dcb933e.png)

Here are the logos :

![red-fail](https://user-images.githubusercontent.com/65908230/131214477-305b9f86-33d6-41e6-b83e-7936b044d071.png)![normal-fail](https://user-images.githubusercontent.com/65908230/131214483-a34bd337-b22c-4f71-8cba-3e2ee2b33a86.png)![red-success](https://user-images.githubusercontent.com/65908230/131214498-75b3db3a-ae8e-4775-9381-c3999ba92df4.png) 
![normal-success](https://user-images.githubusercontent.com/65908230/131214513-f830e924-347e-48f3-9117-0fbca1fbe079.png)![normal-crit](https://user-images.githubusercontent.com/65908230/131214518-a02cc925-3a12-4fed-9d06-cc4c3fcda482.png)![red-crit](https://user-images.githubusercontent.com/65908230/131214520-20a08a41-e38a-428a-84d9-bd055acc49cd.png)
![bestial-fail](https://user-images.githubusercontent.com/65908230/131214521-3fae8b3e-b246-4cba-a23e-1b349406ffe2.png)

CSS modification :

```
/* ChatMessage CSS */

.roll-label {
  font-weight: bold;
  font-size: 130%;
}

.roll-label .danger {
  color: #831515;
}

.roll-label .success {
  color: #18520b;
}

.roll-content {
  font-size: 120%;
}

.uppercase {
  text-transform: uppercase;
}

.roll-img {
  max-width: 100%;
  margin: 1px;
  /*background: rgba(255, 255, 255, 0.5);*/
  border-radius: 0px;
  border: none;
}

.roll-img.hunger-dice {
  /*background: rgba(255, 230, 230, 0.5);*/
  border-color: none;
}

.chat-message .roll-img {
  max-width: 15%;
}

.vtm5e .locked .resource-value-empty:not(.hunger-value) {
  opacity: 0;
  cursor: default;
}

.vtm5e .locked .resource-value-step:not(.hunger-value) {
  cursor: default;
}

.willpowerReroll .die {
  margin-left: 3px;
}

.willpowerReroll .selected::after {
  position: absolute;
  content: 'X';
  font-size: 24px;
  color: red;
  margin-left: -20px;
  margin-top: -2px;
}

#sidebar.app {
  background: rgba(20, 0, 0, 0.9);
}
```
Warning: changing the size of the logo to 15% makes it more readable, but there are now only 8 dices that can be put on a line instead of 10. The solution to make the result even better would be to make the hunger dice appear after the normal dice and not on a line below.

**Comment by Rayji96** [comment]
Did you make the skull image yourself?

**Comment by Gabryel666** [comment]
The original image comes from an android dice launcher application. I reworked the colors, the size and the background with photoshop.

**Comment by eisenfuchs** [comment]
we would probably need to separate icons from backgrounds; I've tried looking up the css shapes but I'm not convinced they actually work. HTML can handle shapes natively tho, so we could theoretically create them using code in the background of the icons.
