### ISSUE TITLE
Item Feature

### ISSUE THREAD

**Issue by Meguido30** [Rayji96/foundry-V5#110]
Hello,
 In item : Feature, in drop-down menu : Merit (In french : atout), flaw (in french : handicaps), backround (in french : historique), 

Possible to add Loresheet (in french : Saga) ?

And add to Characters sheet to Merits

thank thank

**Comment by Rayji96** [comment]
HI sorry I'm having a hard time understanding.
I can add a Loresheet section to features :)
I'm not sure what you mean by drop-down menu?
What is the ask for "And add to Characters sheet to Merits"?

**Comment by Meguido30** [comment]
Hello, I'm integrate Loresheet (Fr : Saga) in Background (item : feature)  for moment.

For weapons and equipment, is there a system ? Roll weapon damage...

Thank for answers

**Comment by Rayji96** [comment]
Is there even weapon damage dice? I though it was all flat modifiers when using weapons?

**Comment by tom959** [comment]
Rayji is right, it is just a simple modifier that gets added after the roll to the damage.

**Comment by Rayji96** [comment]
I'm going to close this. My group has been using backgrounds for loresheets. If anyone else feels strongly about having a loresheet section, I can add it :)
