### ISSUE TITLE
[FEATURE] Willpower Rerolls updating the original message

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#113]
**Is your feature request related to a problem? Please describe.**
Willpower reroll should return a new chat message with the un rerolled dice to calculate successes and keep track of previous ankhs.

**Describe the solution you'd like**
Either send a rerolled message with all the dice or edit the rerolled message

Tasks (Appended so that Github properly displays it in the Issues list view)
- [x] Update the message that the rerolls are made from
- [x] Grey out any rerolled dice
- [x] Insert the new dice in the appropriate spots
- [x] Mark on the chat message with a footer if a point of Willpower damage has been dealt to the actor (if that automation is toggled on)
- [x] Fix the UI of the die selector to look better

**Comment by Veilza** [comment]
I plan to rework the Willpower Reroll system in the near future to:
- [ ] Update the message that the rerolls are made from
- [ ] Grey out any rerolled dice
- [ ] Insert the new dice in the appropriate spots
- [ ] Mark on the chat message with a footer if a point of Willpower damage has been dealt to the actor (if that automation is toggled on)

Additionally...
- [ ] Fix the UI of the die selector to look better
