### ISSUE TITLE
Option to set default Attribute in rolls

### ISSUE THREAD

**Issue by mountogdengc** [Rayji96/foundry-V5#119]
Option to set default Attribute in rolls. IE setting Stealth to use Dexterity by default, Persuasion to use Charisma, etc.

**Comment by Rayji96** [comment]
Hm... how would you handle rolling stealth with a different attribute if the default is set?

**Comment by Layman2501** [comment]
Custom Roll feature already addresses this.

**Comment by Rayji96** [comment]
I'm going to close this as I agree custom rolls address this.
