### ISSUE TITLE
[BUG] dicebox not loading / case sensitivity on linux

### ISSUE THREAD

**Issue by Danii0206** [Rayji96/foundry-V5#122]
Hi,

I was searching for the dicebox in chat window for quite a while but couldn't find it. Then I found an error in console:

Uncaught (in promise) Error: ENOENT: no such file or directory, open '/home/myusername/.local/share/FoundryVTT/Data/systems/VTM5E/templates/ui/tray.html'

The problem is: Paths are case sensitive on linux. The folder VTM5E does not exist, but vtm5e does. Please convert all instances of folder and filenames to be consistent regarding upper/lowercase.

Kind regards
Danii

**Comment by Rayji96** [comment]
Oh shoot good catch
