### ISSUE TITLE
[FEATURE] Combat tracker

### ISSUE THREAD

**Issue by tomot21** [Rayji96/foundry-V5#124]
Use the combat tracker with Vampire V5 rules ( d10 rolls , damage, etc).
Thanks

**Comment by Rayji96** [comment]
can you reference the pages? I must've missed this rule

**Comment by tomot21** [comment]
in the rulebook, pages 123 to 129, there is the rules for the fight.

**Comment by eisenfuchs** [comment]
I am curious, but the way initiative works is:

1. established melee
2. ranged fights 
3. newly established melee

and disciplines allowing blanket priority means there's no initiative roll at all. 

if anything, it would make sense that the combat tracker has a drag and drop functionality, not a roll.
