### ISSUE TITLE
[Translation] German "Dreckiger Erfolg" + "Kranfbonus"

### ISSUE THREAD

**Issue by Danii0206** [Rayji96/foundry-V5#129]
Hi,

I found two minor translation errors for the german version:

- In chat messages for rolls, when a roll is a messy critical, the german translation in this module is "Dreckiger Erfolg". In the rulebook the same would be "Schmutziger Triumph" (p. 207). Which is practically the same meaning, but got my players very confused. ^^

- In the character sheet on the tab for blood there is an entry for a bonus on discipline-rolls. In this module it is translated to "Kranfbonus" (Kranf is not a german word afaik) . In the rulebook it is called "Bonus auf Disziplins-Kraft" (p. 216). "Disziplinsbonus" or "Kraftbonus" should suffice if the other is too long.

Kind regards
Danii

**Comment by tom959** [comment]
Created Pull Request with the requested fixes.
Wenn du weitere Vorschläge zur Verbesserung der Übersetzung hast, kannst du sie mir ruhig mitteilen.

**Comment by Danii0206** [comment]
Danke dir :)

**Comment by tom959** [comment]
The issue has been fixed, it can be closed
