### ISSUE TITLE
[FEATURE] custom rolls should have a field for modifiers

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#138]
**Is your feature request related to a problem? Please describe.**
custom rolls are a good way to work around things or create buttons to cover edge cases not already covered by the system

**Describe the solution you'd like**
a simple text field to enter a modifier, maybe difficulty too for custom roll items

**Comment by SDBowser** [comment]
I had a problem at my table last night, one of my players wanted to create a custom roll for his hunt. However, he has a beauty modifier in which he gains two more dice, there is no such option in creating the custom roll. The option to put some extra modifier on the custom roll should be at creation, or when he was going to roll the custom roll, just like when he was going to roll a skill.


I was going to create a new topic, but looking here in the issues section, I saw that they had already done it a year ago.

**Comment by Veilza** [comment]
This is another thing that I'll probably end up doing myself soonish. It would end up going with my near-future plans of having toggle-able modifiers on various rolls such as skills during Werewolf transformations and bonus dice for vampires affected by drinking resonance associated by certain types of disciplines.

I'm self-assigning for now to add it to my "to-do" list!
