### ISSUE TITLE
Dice Roller not working

### ISSUE THREAD

**Issue by Digitalnamshub** [Rayji96/foundry-V5#139]
**Describe the bug**
When using the dice roller from the character sheet, no 3D dice appear on the screen and no result gets pushed to the chat. It was working fine last night before the update.

**To Reproduce**

1. Go to any Character sheet
2. Click on a skill to roll, various combinations of choices on the pop-up screen for Attribute and modifiers doesn't seem to change anything
3. See error, no dice appear and no results in chat

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser Edge and Chrome
- FoundryVTT  Version 9 - Build 249
- Foundry-V5 Version 1.8.1

**Comment by Digitalnamshub** [comment]
As Gamemaster, if I log out and return to set up, and then reenter game, the results do finally appear in the chat.

**Comment by Rayji96** [comment]
I missed a removed `await` in a pull request that breaks the async nature of the dice roller. Added it back in and tested it locally and on a staging env. Thanks for spotting this critical bug so quickly!
