### ISSUE TITLE
[FEATURE] Adding V20 Discipline to my game

### ISSUE THREAD

**Issue by AiloneHS** [Rayji96/foundry-V5#142]
Hi I'm trying to start a game in the V5 system but with the V20 lore and clans, and I was wondering if there was a way to add the V20 disciplines to those allready implemented be it by creating an item or coding them in but I'm not a great coder and am not sure on how to procede... can anyone give me a hint on how to procede?

**Comment by Rayji96** [comment]
You can fork the repo and create your own V20 system or check the FoundryVTT discord for any V20 support. Unfortunately, I'm only going to be supporting core V5 features so I'm going to mark this as Won't Do.
