### ISSUE TITLE
[FEATURE] Add a modifier to a Custom Roll

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#144]
A proposal:
to add a modifier field to a custom Roll. I.e. a Siren Predator Roll who has Good Looks Merit would get bonus die. 
Could be either a prompt each time a roll is made or (preferred imho) a set modifier editable at an Item level

**Comment by gbursson** [comment]
Duplicate

**Comment by hredua** [comment]
How can i use it? i cant find it
