### ISSUE TITLE
[BUG] Rouse checks on Oblivion do not show proper 1s

### ISSUE THREAD

**Issue by eisenfuchs** [Rayji96/foundry-V5#145]
**Describe the bug**
Rouse checks use standard vampire dice, which is a problem with Oblivion that requires the player to track 10s as well as 1s. For that matter, Rouse checks should use hunger dice; or at least use them when rolling Oblivion.

**To Reproduce**
Roll an Oblivion rouse check; it uses a default vampire die that does not have an identifiable 1 side.

**Expected behavior**
1s should be visible.

**Additional context**
Arguably I'm probably using the wrong report type, I'm sorry. But it makes playing Oblivion impossible with the default Rouse UI.

**Comment by eisenfuchs** [comment]
Besides misusing the bug label, I think it's important to note that we should NOT include a visible 1 on regular dice. Just use hunger dice for Rouse checks instead of normal dice. It will solve the problem.

**Comment by gbursson** [comment]
@eisenfuchs Second that. Plus, _thematically_, it would be appropriate to use Hunger dice to check for, well... Hunger.

**Comment by Rayji96** [comment]
I agree with that. I'll have the hunger dice be the dice for rouse checks.

**Comment by gbursson** [comment]
Also, if possible to code, for Oblivion Powers can possible Stains when '1' or '10' be announced by the system?
As in: "Might cause Stain due to Oblivion being used" or something similar? It would just be a nice to have really, nothing crucial.

**Comment by tom959** [comment]
Any news on that feature? I run into that issue yesterday. Would be nice :)

**Comment by Veilza** [comment]
Already in the system on main, and pull request #203 will make sure this is working on the dev branch again too.
