### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cantra** [Rayji96/foundry-V5#146]
Attribute, Skill, Discipline and Blood Potency dots do not appear to be selectable to increase or decrease, though the ability to click the name in order to roll is properly functioning.  

I'm using Foundry v9, build 269 and v 1.8.2 of the V5 module, English localization.

**Comment by eisenfuchs** [comment]
Did you unlock the character sheet, or what am I missing?

**Comment by eisenfuchs** [comment]
The UI elements for increasing stats only show up when a character is unlocked (right under their portrait).

![Bildschirmfoto 2022-06-07 um 17 05 39](https://user-images.githubusercontent.com/79832708/172414996-cb212e6f-566b-4e62-b254-031fb5e4651c.png)
![Bildschirmfoto 2022-06-07 um 17 05 52](https://user-images.githubusercontent.com/79832708/172415006-3000ef50-abf7-4787-ac5d-6d954e06bb9e.png)

**Comment by Cantra** [comment]
Thank you! I apparently missed that entirely.
