### ISSUE TITLE
[FEATURE] hide Trash icon (Disciplines etc) in Locked mode

### ISSUE THREAD

**Issue by eisenfuchs** [Rayji96/foundry-V5#147]
**Is your feature request related to a problem? Please describe.**
It is very easy to accidentially click the trash icon when you actually wanted to post the discipline power or feature description.

**Describe the solution you'd like**
When the character is in locked mode, the trash icon shouldn't be there. That would make playing the character a tad easier and less likely to end in problems.

**Describe alternatives you've considered**
If there'd be a way to undo an accidential removal that would also be very helpful. If that already exists, it needs to be advertised somehow, maybe through a small notification popup in the lower left corner saying "Push Ctrl+Z to undo" (or whatever).

**Additional context**
![Bildschirmfoto 2022-06-07 um 18 48 46](https://user-images.githubusercontent.com/79832708/172438978-19d859d0-1c48-44a5-b68e-1d47a3942490.png)

**Comment by gbursson** [comment]
That's a __must__, seriously.

**Comment by LorduFreeman** [comment]
I have this fixed and in my own hack already, ready to do a PR - but I'm waiting until the SASS issue gets fixed first. Seems to be only a matter of time.

(How it works: Locking the sheet hides all +/Add XYZ, zero Dot and Trash buttons)
