### ISSUE TITLE
[FEATURE] Roll Willpower 'shortcut' button

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#148]
The green buttons row below chat. Roll Willpower button rolls Willpower dice, as expected, **but** marks Willpower expenditure as well.
Is that an intended behaviour?
![image](https://user-images.githubusercontent.com/1756600/172621335-1b5cdcf5-2476-4093-b2fb-74636a9561ac.png)

**Comment by Veilza** [comment]
Closing this issue because it's being handled by #215
