### ISSUE TITLE
[FEATURE] Add item types for various sheet fields

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#150]
A proposal to add Clan and Predator item types, similar to Boon, CustomRoll etc.
Idea:
One can create Clans / Predator Types, and then drag them onto the sheet, which would autopopulate fields: 
i.e. Clan Bane, one could assign an icon as well
for Predator type it could incorporate a Hunting roll too in addition to auto-pulled description

**Comment by TheBalzan** [comment]
Strong Plus 1 to this.
It would help if the clans and included the base clan disciplines for future reference.
