### ISSUE TITLE
[BUG]Discipline Level Not Storing

### ISSUE THREAD

**Issue by TheBalzan** [Rayji96/foundry-V5#162]
Hopefully, a simple bug to duplicate. But the discipline level number is not being stored on the discipline. I can enter it but the second I close the discipline it will be empty.
This seems to be a new issue as of the recent release of Foundry 10.
I am using Foundry 10.285

**Comment by Rayji96** [comment]
The bugfix will be released with V5 2.0. Figured out the issue :)
