### ISSUE TITLE
[FEATURE] Refactor vtm5e to generic wod5e

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#168]
Just a quick proposal, before I would start refactoring, need a buy-in from the owner.
As you are slowly adding features from Hunter, expanding beyond just Vampire, could we make the prefixes, names etc. (VTM5E, vtm5e) refactored to a more generic (WOD5E, wod5e)?

**Comment by Rayji96** [comment]
Yes and no haha. Because of how foundry IDs systems, the path and system name/ID needs to stay vtm5e. Everything else can use a generic wod5e.

**Comment by gbursson** [comment]
so css classes, prefix for lang.json contents etc. can be modified. I will fork it and make changes, hopefully not breaking anything ;)
