### ISSUE TITLE
[BUG] Stats are cleared when Char shet is locked

### ISSUE THREAD

**Issue by Scratch-code** [Rayji96/foundry-V5#171]
**Describe the bug**
Stats are cleared when Char shet is locked

**To Reproduce**
Unlock sheet
make change
lock sheet and changes are not saved. 

**Expected behavior**
Changes to sheet to be saved

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://drive.google.com/file/d/13cK2RXdyfqVhJAbMVvcok6KrA89P4a2D/view?usp=sharing)

**Desktop (please complete the following information):**

- Chrome
- FoundryVTT Version 10 Build 286
- WoD 5e 1.33.0

**Additional context**

**Comment by Rayji96** [comment]
Could not reproduce.
I think you're using the wrong version of WoD 5e. We're on 2.0.2 now.
One of 2 things might be your issue:
* you updated to foundry V10 and forgot to update VTM5e 1.8+ to WOD5e 2.0+
* you were originally on MrDionysus's WOD5e system and haven't migrated to our combined WOD5e version.

If the second applies to you, you can export your data and import it cleanly to the new WOD5e as MRDionysus's WOD5e was a fork of my VTM5e system.

**Comment by Scratch-code** [comment]
PEBCAK
I had both installed like a muppet.

Removed them both installed the correct version and recreated my world and everything is working as intended, Thanks.

**Comment by Matt-BW** [comment]
I have this issue, I am however on 2.0.2, if you close the sheet it saves fine but if you lock it, it wipes any changes.

I don't think I have the other version installed but its very useful thread, I will check thanks.
