### ISSUE TITLE
[FEATURE] Functionality for disciplines that require two rouse checks

### ISSUE THREAD

**Issue by Zombinado** [Rayji96/foundry-V5#173]
**Is your feature request related to a problem? Please describe.**
Some of the disciplines in VTM require a double rouse check and at the moment the sheet only allows for a single check

**Describe the solution you'd like**
Something along the lines of another checkbox to call for 2 rouse checks instead of one or a drop-down menu to choose the number required

**Describe alternatives you've considered**
Another possibility could be rolling the discipline pulls up a chat card with the required rolls similar to this attack card   
![acbb8cba5e8e16c1a8d75cd4dcf3f2bb](https://user-images.githubusercontent.com/110623928/198312108-0a3a06f0-b920-4d62-b795-16e28df9faea.png)

**Comment by gbursson** [comment]
That should be carefully tested for proper interaction with Rouse check rerolls due to Blood Potency
