### ISSUE TITLE
[FEATURE] make releases similar to pf2e

### ISSUE THREAD

**Issue by AucaCoyan** [Rayji96/foundry-V5#176]
**Is your feature request related to a problem?**
Not really, it's more like a convenience to have releases automation like the pf2e system. So on the manifest key you can write: 
```json
    "manifest": "https://github.com/Rayji96/foundry-V5/latest/download/system.json",
```
and foundry will do the rest.

**Describe the solution you'd like**
To achieve that, we would need some automation, for example [this](https://github.com/foundryvtt/pf2e/blob/master/.github/workflows/cd.yml) release workflow.

**Describe alternatives you've considered**
I believe the devs of pf2e have it done really well.

**Additional info**
[This](https://foundryvtt.wiki/en/development/guides/SD-tutorial/SD03-systemjson) tutorial by foundry.wiki is really good

**Comment by Rayji96** [comment]
Good idea! I'll have to take a look when I get the chance or you can tackle it yourself :)

**Comment by AucaCoyan** [comment]
Sure! I can do it. First let me tackle the webpack/typescript/sass issue, it's a long and big one. After that I can put some thought here 💪🏼
