### ISSUE TITLE
[BUG] Replace `Super-Linter` with many different (used) linters

### ISSUE THREAD

**Issue by AucaCoyan** [Rayji96/foundry-V5#179]
**Describe the bug**
Currently Super Linter fails with `gitleaks`, a linter written in go that checks for keys. Also it needs approval of the mantainer of the project every time a new contribuitor submmits a PR (which is uncomfortable).

**To Reproduce**
Steps to reproduce the behavior: just go to the current PRs, like #169  or #178

**Comment by Rayji96** [comment]
https://github.com/Rayji96/foundry-V5/pull/182 as a stop-gap currently

**Comment by AucaCoyan** [comment]
I did some tests, but I haven't had enough time to make it work :(

**Comment by AucaCoyan** [comment]
Hey, I kept going but I still can't pass the wall of the `node-gyp` error when installing the npm dependencies.
In [this branch `eslint-workflow`](https://github.com/AucaCoyan/foundry-V5/tree/eslint-workflow) I added a workflow to run only `eslint`, (I tried twice 🤣) but in both cases I found this error when running:

<details><summary>expand to see the error</summary>

<blockquote>

Run npm install eslint@8.10.0
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/runner/work/foundry-V5/foundry-V5/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c -- node scripts/build.js
npm ERR! Building: /usr/local/bin/node /home/runner/work/foundry-V5/foundry-V5/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/home/runner/work/foundry-V5/foundry-V5/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.19.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/runner/work/foundry-V5/foundry-V5/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /opt/hostedtoolcache/Python/3.11.1/x64/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /opt/hostedtoolcache/Python/3.11.1/x64/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! gyp ERR! System Linux 5.15.0-1030-azure
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/runner/work/foundry-V5/foundry-V5/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /home/runner/work/foundry-V5/foundry-V5/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-01-11T11_12_05_050Z-debug-0.log
Error: Process completed with exit code 1.

</blockquote>

</details>

Apparently is because it cannot find python in the virtual machine where it installs gyp, but I installed python in a previous step successfully and nothing changed 🤔 .

I will keep doing some other tests for this issue, but this particular task turn out a lot harder than I expected
