### ISSUE TITLE
[FEATURE] Documentation on how to load content

### ISSUE THREAD

**Issue by AucaCoyan** [Rayji96/foundry-V5#180]
**The problem**
I would like to write some documentation on how to load content, it is kinda confusing for the non-initiated foundry players

**The solution**
A clear and concise list of instructions for the current and most commonly used alternatives.

**Additional context**
There is a pin in the discord channel `#wod` that serve this purpose. Also the user `@RinVidor` gave a very clear explanation of what works for him.

This is mostly a remainder issue that I have to pick up some time.

**Comment by CoridanM** [comment]
What kind of content do you mean? For most stuff like creating actors, scenes, etc you should probably use a generalised foundry tutorial. I can't think of too much that's specific to WoD5E that needs its own tutorial.

**Comment by AucaCoyan** [comment]
I mean content related to the book of VtM, not to infringe the dark pack terms, but to show how to do it for new players that come to this ruleset.

For example, in Pathfinder I don't have this problem because the content of the rules is free. So it comes with the foundry system.

**Comment by CoridanM** [comment]
Well, to do that the only way I know is to open up the description for when you add a discipline and type in (or copy/paste from the PDF) the section from the book. So far I think it can only be done per character, not like PF2E where you can create an item to just drag onto the sheet.

**Comment by gbursson** [comment]
> Well, to do that the only way I know is to open up the description for when you add a discipline and type in (or copy/paste from the PDF) the section from the book. So far I think it can only be done per character, not like PF2E where you can create an item to just drag onto the sheet.

On the contrary. You can (and should) pre-create Power items at the very least, then it is a matter of dragging those on the char sheet.

See screenshot. Nevermind it's Polish. I have those pre-created (granted, it took some time), now I just drag the item and the char has it, it uses char's Attrbiutes etc.

![image](https://user-images.githubusercontent.com/1756600/210575558-12dca995-ee77-4109-ad85-3a9749b64777.png)
