### ISSUE TITLE
[FEATURE] Animal sheets for Bond Famulus/Coterie Sheets

### ISSUE THREAD

**Issue by CoridanM** [Rayji96/foundry-V5#181]
**Is your feature request related to a problem? Please describe.**
The standard ghoul sheet isn't really useful for Bond Famulus, There's no Coterie sheet

**Describe the solution you'd like**
A generic sheet that can be used for animal ghouls (with Physical/Mental dice pools, etc) and a sheet for Coterie type/backgrounds/domain

**Describe alternatives you've considered**
Using the pre-existing ghoul sheets

**Additional context**

**Comment by gbursson** [comment]
There is a Coterie sheet type.

As for Bond Famulus, I would agree it might be a good QoL idea.

**Comment by Rayji96** [comment]
What more would an animal sheet have over an SPC sheet?

**Comment by CoridanM** [comment]
Honestly, I think just updating the SPC sheet to have full discipline features like other sheets would be enough (and could be handy for making SPCs too so I can just give them specific powers)
