### ISSUE TITLE
[FEATURE] Notes Visible on "Limited" Permissions

### ISSUE THREAD

**Issue by firesidewizard** [Rayji96/foundry-V5#184]
**Is your feature request related to a problem? Please describe.**
I am unable to have *some* information still available for players while the actor sheet is set to limited view.

**Describe the solution you'd like**
I would like to have the 'Notes' block of an Actor Sheet still visible to all players when the sheet itself is set to 'Limited.' This would allow my players to still see some information they are allowed to have ( Like who the NPCs is, their title, etc.) while all their stats would still remain hidden.

**Describe alternatives you've considered**
I've considered doing journal entries for all the NPC information that would be displayed like this -- but that seems redundant.

**Additional context**
The 'Limited' view of the character sheets still has the white-space where the normal data shows. Hopefully this would be something you could just tag the data field for 'Notes' to still show while the 'Limited' option is applied.

**Comment by eisenfuchs** [comment]
Hey. I'm a UX architect, and may I propose a different route?

Instead of making Notes visible on limited, why not add a new section to the character sheet that is called "Public Notes" that's always readable? It could contain obvious descriptions, without making the Notes section unusable for secret note-taking.

**Comment by firesidewizard** [comment]
> Hey. I'm a UX architect, and may I propose a different route?
> 
> Instead of making Notes visible on limited, why not add a new section to the character sheet that is called "Public Notes" that's always readable? It could contain obvious descriptions, without making the Notes section unusable for secret note-taking.

This would be even better. Still allowing the GM to have private notes, while letting the players see what they need.
