### ISSUE TITLE
[FEATURE] Expanded Biography tab

### ISSUE THREAD

**Issue by CoridanM** [Rayji96/foundry-V5#185]
Just a suggestion to have Biography + Appearance moved to a separate tab, and give it a few more fields such as DOB/DOD/Apparent Age/Hair/Eyes/Height/Weight such as on MrGone's sheets.

**Comment by CoridanM** [comment]
One important thing to note is there's no field for Generation on the current sheets.

**Comment by WisdomOfWombats** [comment]
There isa Generation field, as soon as you fill in the Clan field. Then, all the necessary fields appear on the description tab.
