### ISSUE TITLE
Character Sheet Dot Markers Don't Save [BUG]

### ISSUE THREAD

**Issue by 19Dawgmeat** [Rayji96/foundry-V5#187]
**Describe the bug**
Players and GM are trying to input the status on the vampire character sheet however none of the dots save when going to a different screen.

**To Reproduce**

Using chrome
1. Open character sheet
2. Select any dot for stats or abilities
3. Click a new tab then return to old tab
4. Dots are gone

**Expected behavior**
The dots save when you click them.

**Screenshots**

**Desktop (please complete the following information):**

- Browser Chrome
- FoundryVTT Version Version 10 291
- Foundry-V5 Version 1.3.0
**Additional context**

**Comment by Rayji96** [comment]
The wrong version was installed off Forge
