### ISSUE TITLE
[BUG] Players can't expand power items on sheet

### ISSUE THREAD

**Issue by CoridanM** [Rayji96/foundry-V5#191]
**Describe the bug**
People with the Player role can't expand their discipline powers on their character sheet. They can send it to chat but can't just expand to view it.

**To Reproduce**

1. Be a player
2. Have a discipline power on your sheet
3. Click on the name to expand the power
4. Compare same attempt while having the GM role.

**Expected behavior**
Players should be able to see the text for their discipline powers without having to send it to the chat.

**Comment by Rayji96** [comment]
What version of Foundry and foundry-V5 are you using?

**Comment by CoridanM** [comment]
Ah, I was on V10 still with 2.0.2 now I'm on V11 and 2.0.2 and it's working
