### ISSUE TITLE
[BUG] White text one white background once updated to Foundry v11

### ISSUE THREAD

**Issue by SalithTaydan** [Rayji96/foundry-V5#195]
**Describe the bug**
Text in title blocks of items are white text on a white box.

Also, expanding folders in compendiums shows white text on white background.

**Comment by SalithTaydan** [comment]
![Foundry VTT V5 A](https://github.com/Rayji96/foundry-V5/assets/64750331/5d56b17e-4b29-40ee-b3a0-6bf88dafd60a)
![Foundry VTT V5 B](https://github.com/Rayji96/foundry-V5/assets/64750331/64ff304c-143c-4f8e-af59-2fcebc5e8854)

**Comment by Rayji96** [comment]
That's what I get for not testing Darkmode :(
I'll take a look thanks for pointing it out
