### ISSUE TITLE
Support for Werewolf 5th edition

### ISSUE THREAD

**Issue by Lachrimae93** [Rayji96/foundry-V5#196]
Are there any plans to support a character sheet for the newly released werewolf 5e? Just wondering what the timeline on that is if there are plans to do so.

**Comment by SDBowser** [comment]
That would be great, I would like to know too.

**Comment by Lachrimae93** [comment]
> That would be great, I would like to know too.

Same. But it looks like no one cares to read or respond on future plans so I'm not holding my breath

**Comment by eisenfuchs** [comment]
I think, it would be wonderful to have the option. But also I think we need to figure out a way to better group powers apart from different systems. When I'm exporting my set, they all get lumped in without any distinctions, and that's bad.

**Comment by SDBowser** [comment]
> I think, it would be wonderful to have the option. But also I think we need to figure out a way to better group powers apart from different systems. When I'm exporting my set, they all get lumped in without any distinctions, and that's bad.

Maybe this would be a suggestion for enhancement, a way to organize creation a little better, according to the scenario, these options for disciplines, gifts, perks, features, etc... 
Try to create another topic for this, in this case, we're waiting, unfortunately I can't contribute to the programming part, so... We're waiting for people who know...

**Comment by Rayji96** [comment]
I'll start work supoorting it as soon as I get my hands on it an read through it. It's not out yet, right?

**Comment by imynwulf** [comment]
I received my pdf weeks ago, and got my hard copy last week. Official release is the 31st, iirc

**Comment by SDBowser** [comment]
on discord of WoD:
![image](https://github.com/Rayji96/foundry-V5/assets/50637773/63dfbc11-e05e-4f17-b61f-aaed71910448)

" 
You can still pre-order it to receive your PDF today:
https://renegadegamestudios.com/werewolf-the-apocalypse-5th-edition-core-rulebook/

To celebrate, we'd like to share with you a brand new Werewolf: The Apocalypse dev diary - The Road to Werewolf - about the journey we took to bring you this release, key changes and ideas behind it, and more!

https://www.worldofdarkness.com/news/the-road-to-werewolf-the-apocalypse-5th-edition
"

**Comment by Lachrimae93** [comment]
> I'll start work supoorting it as soon as I get my hands on it an read through it. It's not out yet, right?

I believe it is. I received my pre ordered pdf already

**Comment by eisenfuchs** [comment]
It's out already, yes. Preorders have been shipped already.

**Comment by Lachrimae93** [comment]
Any idea when support might be available for this (if there are plans to support at all)?

**Comment by Rayji96** [comment]
I'd like to start working on Werewolf support ASAP but my current day job is requiring my full attention unfortunately :(
Right now it's TBD.

**Comment by Veilza** [comment]
I should start being able to work on Werewolf support soonish. I'm making a branch for it shortly and when I get the book itself I'll start tinkering with things.

So, it's on the way!

**Comment by CoridanM** [comment]
Looks great, so we're just waiting on it to get merged in then?

**Comment by Lachrimae93** [comment]
I'm confused because I see the code and everything here but no actual way to put it in my foundry? The module doesn't have an update

**Comment by Veilza** [comment]
> I'm confused because I see the code and everything here but no actual way to put it in my foundry? The module doesn't have an update

There's still a couple of things that need to be done before the code gets officially merged. Namely, the main thing is I know someone else is working on the dice faces for the Werewolf/Rage dice. But it's not too far away and whenever that happens and @Rayji96 has the time to look things over, it should be good!

**Comment by Lachrimae93** [comment]
> > I'm confused because I see the code and everything here but no actual way to put it in my foundry? The module doesn't have an update
> 
> There's still a couple of things that need to be done before the code gets officially merged. Namely, the main thing is I know someone else is working on the dice faces for the Werewolf/Rage dice. But it's not too far away and whenever that happens and @Rayji96 has the time to look things over, it should be good!

Oh I see. I'm sorry I thought it was already available and I just wasn't able to install it for some reason. Thanks!
