### ISSUE TITLE
[FEATURE] Factor in Power Bonus and Resonance Bonus to Discipline Rolls

### ISSUE THREAD

**Issue by CoridanM** [Rayji96/foundry-V5#202]
Blood Resonances and Bloot Potency add bonus dice to uses of Disciplines. This should be factored in when rolling disciplines straight off the sheet. It would require changing the blood resonance to a dropdown instead of a typed field probably.

**Comment by f-fabner** [comment]
I think the idea is very valid, adding, instead of writing which resonance, simply choosing one, and thus adding extra dice rolls in the appropriate disciplines...

**Comment by eivil** [comment]
Agreed. Another option, though i'm not sure how feasible it would be to implement, is tying resonance (and maybe even impairment) to custom conditions appliable to tokens for easy visualization.

The discipline bonus from Blood Potency is already factored when you roll it from the power icon ![Sem título](https://github.com/Rayji96/foundry-V5/assets/102497677/287084a9-9142-4136-835c-1722ed425663) , tho it would be useful to extend that to general discipline roll buttom

**Comment by Veilza** [comment]
I can look into adding this in some form soon! I can't promise how I'll implement it but I'll at least make sure that some update to the resonance system is in my plans.
