### ISSUE TITLE
[BUG] Werewolf text sheets not displaying the information they contain

### ISSUE THREAD

**Issue by CristianLemeni** [Rayji96/foundry-V5#213]
When I fill in the text fields for convictions, tenets, biography etc they don't show the info unless it's in edit mode.

![Screenshot_114](https://github.com/Rayji96/foundry-V5/assets/37481559/32e5925e-f5b6-44b3-858f-0ef8d0116c73)
![Screenshot_115](https://github.com/Rayji96/foundry-V5/assets/37481559/dc081ece-c190-4a07-85f9-35cd6ab075c1)

This is for the werewolf sheets in the last pre-release version.

**Comment by Veilza** [comment]
Issue should now be fixed with the latest commit. Releasing a new prerelease soon that will include the fix.

**Comment by Veilza** [comment]
Now fixed with [Prerelease 3](https://github.com/Rayji96/foundry-V5/releases/tag/3.0.0-prerelease3).
