### ISSUE TITLE
[BUG] Hunter Sheet Edge not rollable

### ISSUE THREAD

**Issue by CristianLemeni** [Rayji96/foundry-V5#214]
When setting a hunter edge to rollable, it doesn't show the dice button and you can't roll it.

This is on the latest pre-release version.
![Screenshot_120](https://github.com/Rayji96/foundry-V5/assets/37481559/51b6bdd2-f4e1-4f77-8c0b-f584ce9ce872)

**Comment by Veilza** [comment]
Hm! Very strange, I don't know how this got broken in the first place, but I'm working on a fix right now.

Thank you for reporting this!

**Comment by Veilza** [comment]
Now confirmed fixed in the latest [prerelease 4](https://github.com/Rayji96/foundry-V5/releases/tag/3.0.0-prerelease4)
