### ISSUE TITLE
[BUG] Can't create an actor

### ISSUE THREAD

**Issue by Azkarna** [Rayji96/foundry-V5#216]
**Describe the bug**
Pretty simple, the console throws an error when I try creating an actor/character using the prerelease version. I have no modules enabled and it appears to be an issue with the actor script itself

**To Reproduce**

1. Go to 'Actor Tab'
2. Click on 'Create Actor'
3. See error

**Expected behavior**
To be able to create a character.

**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/65684060/3bda9fb0-7bc8-40a0-81a3-2ee3c82983c8)

**Desktop (please complete the following information):**

- Browser [None being used atm]
- FoundryVTT Version [10]
- Foundry-V5 Version [Prerelease 4.0.0]

**Comment by Azkarna** [comment]
actorTypes[actorType] = actorTemplates[actorType].label ? game.i18n.localize(actorTemplates[actorType].label) appears to be the source of the problem, manually deleting everything after the ? fixes the issue for me.

**Comment by Veilza** [comment]
After testing things on my own machine, I can confirm this is a V10 exclusive bug and not one that I'm willing to look into fixing, considering after digging into things I would have to fix a few more things than just this to make the system compatible with V10 moving forward.

The overhaul of changes between V10 and V11 as well as the changes I've done between the current release and the current prerelease just doesn't make it worth the effort to make sure the system, moving forward, is compatible with the old FoundryVTT system.

Until someone else is willing to figure out how to make it compatible with previous versions, I'm closing this issue. But! This issue did inform me that I need to set the current prerelease as V11 minimum compatible.
