### ISSUE TITLE
[FEATURE] Let users add custom disciplines

### ISSUE THREAD

**Issue by Lemantia** [Rayji96/foundry-V5#220]
**Is your feature request related to a problem? Please describe.**
Adding custom disciplines (such as from the Remastered Disciplines on storyteller vault https://www.storytellersvault.com/product/429353/Chimerstry-Remastered?language=en) is made complicated by the fact that we can't roll or have dots in those specific disciplines.

**Describe the solution you'd like**
A settings to add custom disciplines to add to the dropdown menu of the Power items.

**Comment by Veilza** [comment]
I mentioned this in the Discord already, but just for posterity / issue tracking, I do have plans to implement this in the future! No timeline as of yet, since I have a lot planned already, but rest assured its on the list.
