### ISSUE TITLE
[BUG] Can't Willpower re-roll Hunter and Werewolf dice

### ISSUE THREAD

**Issue by CristianLemeni** [Rayji96/foundry-V5#223]
After upgrading to the latest pre-release version I can't seem to willpower re-roll rolls made from the hunter and werewolf sheets

Here's some screenshots from the Hunter and Werewolf ones compared to the Vampire(which work).
![Screenshot_144](https://github.com/Rayji96/foundry-V5/assets/37481559/b054f054-390e-4bb0-9d6d-2aea1838d1bc)
![Screenshot_145](https://github.com/Rayji96/foundry-V5/assets/37481559/80c0088c-03ab-431f-9edc-89d5343e17f6)
![Screenshot_146](https://github.com/Rayji96/foundry-V5/assets/37481559/fdf8486b-bb46-48a2-a114-5c1c1167a34a)

**Comment by Veilza** [comment]
Ah, I see how this got broken with the most recent update to the dice. Thank you for reporting this! It should be fixed shortly.

**Comment by Veilza** [comment]
Now fixed with commit 36ba27d5363f1c9e7bcbb2954a815224cf661011
