### ISSUE TITLE
[FEATURE] Please use white symbols on the hunger dice 

### ISSUE THREAD

**Issue by WisdomOfWombats** [Rayji96/foundry-V5#224]
The contrast between the red hunger dice and the black symbols isn't very user-friendly to people with issues like color-blindness or congenital red–green color blindness and variations there off.

Could you please use white symbols on the red hunger dice? I understand the desire to be as close as possible to the official dice, but those are also an issue for people with congenital red–green color blindness and variations there off. Modiphius had the right idea to use white symbols.

Alternatively, introduce a setting option for using white dice symbols both on the Dice So Nice integration and in the chat messages. From what I understand, some users prefer the new red/black coloring scheme.

**Comment by gbursson** [comment]
Second that. Straight after updating to 3.0.0 noticed that and came here to file the Issue.

**Comment by Veilza** [comment]
This is actively being worked on and should be fixed with the next release.
