### ISSUE TITLE
Simple NPC sheet

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#23]
Summary:
Antagonist stats sheet for quick reference of NPCs that cover Standard Dice Pools, Secondary Attributes, etc.

Acceptance Criteria:
- Easy to edit, organized, NPC sheet
- Covers different types of NPCs/Antagonists
- Dice Pools are organized and rollable.

**Comment by eisenfuchs** [comment]
Ah, this is something I really would like to have; but so far I'm not up to speed with sheet creation. I have some vague ideas for how it should look (UX wise), but that's probably not relevant at the moment. Having a Pools section with the possibility to add and NAME custom pools is a must, and I'm looking for this kind of thing, to make the metamorphosis from protean easier for me. Currently I'm using a duplicated character sheet.

**Comment by TheBalzan** [comment]
I feel this is an essential feature that should be added to the game as soon as possible. Would make life so much easier when statting creatures or transposing solely into Foundry.
