### ISSUE TITLE
[BUG] Features' description not showing on click

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#231]
Descriptions of Features (Merits/Flaws/Backgrounds) do not show when the item is clicked.
It works for Discipline powers

1. Go to character sheet
2. Click on any Feature
3. No Description showing
4. Works for Powers of Disciplines

**Expected behavior**
Clicking on a Feature name should expand the Description

**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/1756600/96b6dc8a-c3e2-4f96-9089-b036615d1826)

**Comment by Veilza** [comment]
Already known and fixed in the upcoming release.
