### ISSUE TITLE
[BUG] Features tab descriptions on all sheet types

### ISSUE THREAD

**Issue by Zombinado** [Rayji96/foundry-V5#236]
**Describe the bug**
The collapsible descriptions on the features tab seem to have stopped working for Backgrounds, Merits, Flaws, and Boons.

**To Reproduce**

1. Create a Vampire, Ghoul, Mortal, Coterie, Hunter, Cell, Story Character, or Werewolf sheet
2. Add a feature item through either on sheet creation or drag from items
3. Click on the name of the item (It will react with a glowing outline)
4. Nothing happens, no errors in the console either

**Expected behavior**
A white text box opens below the item to display the description 

**Screenshots**

**Desktop (please complete the following information):**

- Browser Firefox and the Foundry software
- FoundryVTT Version 11 build 315
- Foundry-V5 Version 3.0.0

**Additional context**

**Comment by Veilza** [comment]
This is known about and is going to be fixed in the next release.
