### ISSUE TITLE
[FEATURE] Function to just roll X number of dices

### ISSUE THREAD

**Issue by JohanFalt** [Rayji96/foundry-V5#245]
a function or description to roll just a few none connected dices.

say you forgot to add a bonus to a roll.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Veilza** [comment]
This technically would be resolved by #215, as the dice roller is *supposed* to be where you roll things that aren't handled by the sheets themselves.

**Comment by gbursson** [comment]
Hey there. It is not integral to the module, but maybe my simple macro would be of use?
It relies on the Special Dice Roller

```
// uses Special Dice Roller [https://github.com/BernhardPosselt/foundryvtt-special-dice-roller]

let text = 'Roll'

let dice_qty = await Dialog.prompt({
    title: `How many dice? (${text})`,
    content: `<input type="text" autofocus>`,
    callback: (html) => html.find('input').val()
    })

let flavor = `<span style="font-size: 1.5rem; font-weight: bold;">${text}</span>`

roll = game.specialDiceRoller.v5.rollFormula(`${dice_qty}` + 'h') // Uses Hunger dice, to change to normal dice replace 'h' with 's'

ChatMessage.create({content: roll, flavor: flavor})
```

**Comment by JohanFalt** [comment]
Thanks! Worked as a charm
