### ISSUE TITLE
[FEATURE] add edit main Discipline description 

### ISSUE THREAD

**Issue by JohanFalt** [Rayji96/foundry-V5#246]
if you add a discipline to a sheet you can’t edit it’s description afterwords.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Veilza** [comment]
How so? On my end you're able to edit discipline descriptions by expanding it (clicking on the Discipline's name) and then just editing the description in the textfield.

Or do you mean the discipline powers?

**Comment by JohanFalt** [comment]
Oh! Look at that. Yes that works.

I just got confused in this case as I thought the function was the same as the discipline powers.
