### ISSUE TITLE
[BUG] Discipline description can't display journal links

### ISSUE THREAD

**Issue by JohanFalt** [Rayji96/foundry-V5#247]
**Describe the bug**

If you link a journal entry to the description of the sheet this is not visible as you view the description of it. See image.

![image](https://github.com/Rayji96/foundry-V5/assets/57871596/163f8c5b-7e39-4375-81dc-2d3a450faab9)

Reason for this is that the text in item.system.description isn't run with enrichHTML before displaying it (see solution below).

**To Reproduce**

Have a discipline, drag a journal entry to the description.

**Expected behavior**

Have the link visible on the sheet.

**Solution**

In helpers.js add:

Handlebars.registerHelper('enrichHTML', function (text) {
    return TextEditor.enrichHTML(text, {async: false});
  })

In templates\actor\parts\vampire\disciplines.html

Line 96 alter:

{{{item.system.description}}} to {{{enrichHTML item.system.description}}}

**Comment by Veilza** [comment]
This should be fixed with pull request #250 -- thank you for the issue report and a suggestion for how to fix things!
