### ISSUE TITLE
[BUG] Ghoul sheets can't roll

### ISSUE THREAD

**Issue by CoridanM** [Rayji96/foundry-V5#249]
**Describe the bug**
Can't roll from Ghoul Sheets

**To Reproduce**
Try to roll from a ghoul character sheet

- Browser [chrome]
- FoundryVTT Version 11-315
- Foundry-V5 Version 3.1.1

SPC, Vampire, Mortal sheets work fine. Have not tested Werewolf/Hunter.

**Comment by Veilza** [comment]
This has been fixed as of commit 77c76ba and will be released with the next update!
