### ISSUE TITLE
[BUG] WP re-roll on rage dice converting the results

### ISSUE THREAD

**Issue by eivil** [Rayji96/foundry-V5#252]
While 3.1.2 added re-rolling of non-brutal Rage dice, when doing so, the resulting re-rolls are converting rage dice into regular werewolf dice.

![image](https://github.com/Rayji96/foundry-V5/assets/102497677/64dd9ba4-9fa3-40e3-aa05-72db3144956e)
![image](https://github.com/Rayji96/foundry-V5/assets/102497677/ea8c3896-d51d-4c7c-ae92-78362682f0b0)

**Comment by Veilza** [comment]
I debated whether to fix this with the code as-is or wait until the full rework of willpower rerolls. It was a tough call but, I decided to just fix this issue for now since I won't be able to get to reworking the willpower reroll system until after New Year's.

Now fixed with pull request #253
