### ISSUE TITLE
[FEATURE] Expendable/Markable Features (advantages, flaws, loresheets)

### ISSUE THREAD

**Issue by eivil** [Rayji96/foundry-V5#259]
I think the system would benefit from some way of displaying "used" features in the character sheet. Some Features can be expended, used or damaged during game, becoming unavailable for some period of time. Having a way of diferentiating these in some way would be great.

Some use cases that come to mind:
- Each dot in Herd can be used once per week, and individual dots can become damage (in failed frenzy checks or messy crits/bestial failures)
- Extremely large purchases with resources may render some dots unusable until the end of the current story
- Many Loresheets merits can be usable "once per story"
- For Storytellers, unmarked flaws like Enemy/Adversary could be an useful reminder that these flaws haven't showed up in the current story

I made a simple mockup of how it could look, with filled/empty dots representing avaiable and unavaiable/damaged/spent dots, and striketrough text as a complementary marking for the entire feature.
I have some more suggestions for the Features section, but I think I'll wait to see what the people working on it are planning.

![image](https://github.com/Rayji96/foundry-V5/assets/102497677/0316bb0c-d6d4-43de-b4f2-43bc53201bc3)

**Comment by Veilza** [comment]
Oooh this is a good idea! I'll definitely add it to my to-do list and try to implement it sometime in the future.
