### ISSUE TITLE
[BUG] Visual glitch with the player limited view of NPCs

### ISSUE THREAD

**Issue by victor-am** [Rayji96/foundry-V5#263]
**Describe the bug**
Looks like the CSS of the actor-header doesn't play well with the portraits:
<img width="677" alt="image" src="https://github.com/Rayji96/foundry-V5/assets/13217785/0f3182f5-61f2-43f2-83d1-b03e71abc4b8">

I noticed that just adding `flex-wrap: wrap;` to the `.actor-header` class fixes the issue (example below in the expected behavior) but I'm not sure if it would break something else so I didn't open a pull request.

**To Reproduce**

1. Just give players Limited ownership to a NPC
2. When they try to see the sheet the issue described above should happen

**Expected behavior**
I suppose something like that:
<img width="677" alt="image" src="https://github.com/Rayji96/foundry-V5/assets/13217785/0c47dd93-eb15-4809-b7ab-42535c61a019">

**Screenshots**
Added above

**Desktop (please complete the following information):**

- FoundryVTT Version 11 build 315
- 4k monitor

**Comment by Veilza** [comment]
Thanks for submitting an issue! I'll look into it and make sure a fix gets put out soon.

**Comment by Veilza** [comment]
Should be fixed with 9460f59eff69a384408c733b37c6ad06e85e95ca
