### ISSUE TITLE
[BUG] Sheets don't add the animal ken skill dice to the total dice pool roll

### ISSUE THREAD

**Issue by CristianLemeni** [Rayji96/foundry-V5#278]
![Screenshot_235](https://github.com/Rayji96/foundry-V5/assets/37481559/569ba287-20d2-4edd-8563-2e2c0d22d276)
When using the animal ken skill on any type of sheet it doesn't add the skill to the actual roll.

**Comment by Veilza** [comment]
Thanks for letting me know! Should be fixed before the full 4.0.0 release.
