### ISSUE TITLE
[BUG] Bonuses not appearing in custom modifiers list

### ISSUE THREAD

**Issue by Zombinado** [Rayji96/foundry-V5#283]
not sure if you'd rather I split these up but I have a feeling they are all related

**Describe the bug**
<u>Werewolf Sheet</u>
Background tied to attributes or skills doesn't show up
Merit/Flaw tied to attributes or skills doesn't show up
Boon tied to attributes or skills doesn't show up
Gifts seem to work ok if they are tied to a skill 
Gifts seem to fail if they are tied to an attribute
Custom rolls bonus created on the custom roll doesn't show up but specialties do

<u>Vampire Sheet</u>
Background tied to attributes or skills doesn't show up
Merit/Flaw tied to attributes or skills doesn't show up
Boon tied to attributes or skills doesn't show up
Custom rolls bonus created on the custom roll doesn't show up but specialties do

<u>Hunter sheet</u>
Edge tied to attributes or skills doesn't show up
Background tied to attributes or skills doesn't show up
Merit/Flaw tied to attributes or skills doesn't show up
Boon tied to attributes or skills doesn't show up
Custom rolls bonus created on the custom roll doesn't show up but specialties do

Ghoul and mortal sheets seem to react the same as vampire

**To Reproduce**
All items were created to drag and drop except for custom rolls, all items were set up as is out of the box 
item added to the sheet 
attempted to roll the skill connected to the bonus

**Expected behavior**
The bonuses to show up in the same space as the specialties 

**Screenshots**

**Desktop (please complete the following information):**
- Browser the foundry app
- FoundryVTT Version 11 stable 315
- Foundry-V5 Version Pre-release 3

**Additional context**
Testing was done in a freshly created world
These are going to be SO GOOD when they are behaving for you! Thank you

**Comment by Veilza** [comment]
Oh! I know why this is happening. It's because of the structure of Items not allowing the situational modifiers script to see their bonuses.

Thank you for finding this! It seems I had tested this on everything **except** items...

I'll make sure a fix gets put out soon.

**Comment by Veilza** [comment]
There we go, I managed to fix it and I'll have a pull request merged before 4.0 drops. Thanks again! I'll close this issue when I merge things.
