### ISSUE TITLE
[BUG] Edit Speciality for Skill Doesn't Work Properly

### ISSUE THREAD

**Issue by humancomputor** [Rayji96/foundry-V5#285]
**Describe the bug**
It seems like after a few edits in the same skill for a specific specialty, cached information is presented instead of stored in the last edit.

**To Reproduce**

1. Add a new specialty to a skill(e.g. Insight).
2. Set a title (e.g. Lies)
3. Add another specialty leaving the title as "New Speciality"
4. Change "Active When" to "Is equal..."
5. Click "Add"
6. Close the popup and reopen(You have to because the edit icon doesn't respond)
7. Change "Active When" to "Always" for the "New Speciality"
8. Change "Active When" to "Never" for the "New Speciality"
9. Click Edit and see that the state of "Active When" seems to be from the previous edit aka "Always"(step 7)

If you close the skill window and reopen it, the edit specialty popup info is populated correctly

**Expected behavior**
After editing the speciality should be populated with proper information

**Screenshots**
<img width="400" alt="FIrst Speciality" src="https://github.com/Rayji96/foundry-V5/assets/12181746/47a203ed-6f24-4180-b279-539c8d8174a9">
<img width="806" alt="Edit Behevier" src="https://github.com/Rayji96/foundry-V5/assets/12181746/dbf57ca5-86af-44ea-a01e-7c291a20898e">

**Desktop (please complete the following information):**

- Browser Safari
- FoundryVTT Version 11 Build 315
- Foundry-V5 Version 4.0.0 Prerelease 3

**Additional context**
I did a lot of edits and additions to the skill, so I'm not sure if it is related. But even after I delete all the specialties, I can reliably reproduce the issue.

I hope it helps to fix the issue, I might make a video If needed. And btw a pretty solid update, some fantastic features are added in this release. Keep up the good work! Thanks!

**Comment by Veilza** [comment]
After some testing of my own, I *think* I know why this is happening. I'll look into it further! Thank you for bringing up this issue and I'll make sure it gets fixed soon.

**Comment by Veilza** [comment]
Okay! I managed to fix the issue. Pushing a fix to the dev branch in just a minute, and the problem shouldn't happen once a stable release is put out. Once again, thanks for letting me know about this issue!

**Comment by humancomputor** [comment]
You're welcome. My duty to help:]
