### ISSUE TITLE
Fix French Localization

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#30]
Summary:
Messy Critical and Bestial Failure show the opposite of what they should. I should look through to see any other mistakes in both French and Brazilian Portuguese localizations.

Acceptance Criteria:
- localizations properly translate what they should

**Comment by Reiaka** [comment]
Hello, I tried to check French translation and I have seen only two modification for now
`"VTM5E.Abilities": "Attributs",`
`"VTM5E.ClanBane": "Fléau de clan",`

**Comment by Meguido30** [comment]
hello
Test system
Why if Succès : 0 not message Echec! in chat ?

test Bestial failure ok in Foundry French : Potentiel Echec Bestial! when hunger dice is "1"
test critiqual succes ok in Foundry french : Succès Critique! when 2 dice is "10"
test messy critical ok in Foundry French : Succès Triomphal! whend 1 dice "10" and hunger dice "10"

if you want I can start french (and english more) compendium I have foundry vtm vampire5 database and trad in french

**Comment by Rayji96** [comment]
@Reiaka Thank you for looking through! Help is greatly appreciated :smile:

@Meguido30 Thank you for the feedback! Failure and success are only shown if you provide a difficulty to the roll. I think showing Echec/Fail on 0 successes even without providing difficulty might begin crowding the roll messages.

**Comment by Rayji96** [comment]
What kind of compendium? If it's a list of localizations that would be greatly appreciated but I cannot provide licensed book materials like a compendium of disciplines, clans, etc.

**Comment by Meguido30** [comment]
Hello,Top !! , everithing work, I forgot Difficulty oopp :) :) thankenvoyé : 7 janvier 2021 à 19:24de : Ray Ji <notifications@github.com>à : Rayji96/foundry-V5 <foundry-V5@noreply.github.com>cc : Meguido30 <alain.barbato@orange.fr>, Mention <mention@noreply.github.com>objet : Re: [Rayji96/foundry-V5] Fix French Localization (#30) @Reiaka Thank you for looking through! Help is greatly appreciated 😄@Meguido30 Thank you for the feedback! Failure and success are only shown if you provide a difficulty to the roll. I think showing Echec/Fail on 0 successes even without providing difficulty might begin crowding the roll messages.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Meguido30** [comment]
hello, Item Power : miss skills for power rolls
thank

**Comment by Meguido30** [comment]
hello
For Power, possible to add Difficulty in item power ? or In disciplines tab, it is possible to have dice roll window for powers in order to manage difficulty

**Comment by Rayji96** [comment]
Like a set difficulty to compare against every time? No. There's a difficulty dialogue you can use though whenever you make a roll from the sheet.
What do you mean miss skills for power rolls?

Either way, this ticket is for fixing french localization. Try to keep it relevant to fixing french localization. If you have questions, the repo README has ways to contact me. If you've found a different bug, make a new bug ticket. 😄

**Comment by Meguido30** [comment]
Hello, Item Power
For Exemple : Bond Famulus ... System Charisma+Animal ken roll (DIFFICULTY 2)
When I click on Bond Famulus icon in character sheet, it rolls dice pool but it does not take into account difficulty of 2

**Comment by Rayji96** [comment]
If this is a bug with the difficulty dialogue, please make a new bug :)

**Comment by Rayji96** [comment]
I can't reproduce your issue @Meguido30 . If you can create a new issue and link screenshots/steps to reproduce that would be greatly appreciated :).

Either way, I'm going to lock this thread to prevent further derailment from fixing the french localizations lol.

**Comment by Rayji96** [comment]
This was a general ticket for tackling translations. I'm closing this ticket but encouraging y'all to create specific bugs :)
