### ISSUE TITLE
[BUG] Incomplete Migration

### ISSUE THREAD

**Issue by f-fabner** [Rayji96/foundry-V5#300]
**Describe the bug**
After the update, the old character and NPC sheets did not migrate correctly to the new system.

**To Reproduce**
I'm not sure if it's possible to reproduce this bug, or if I'm overlooking something, but just by opening the sheet, the problem becomes evident.
And I'm not sure if it's a translation issue, but I've simply disabled all my modules, I changed and then reverted the language, and still the issue persists, only with old sheets. The sheets that are created don't have any issues, so I believe it might have been something during the migration.

**Expected behavior**
The sheets are showing with the following abbreviation in front: WOD5E.(attribute or skill) When they should only have the skill and/or attribute showing
**Screenshots**
Old sheet:
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/43c70e87-ce3c-4c13-9a5e-f2d878cf682b)
New Sheet:
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/613caa2c-517f-48ef-ba9e-a8b405e7f62b)

**Desktop (please complete the following information):**

- Browser [edge, chrome, and firefox(tested on my pc and my players....]
- FoundryVTT Version [11]
- Foundry-V5 Version [4.0.1]
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/2e5ab745-db51-4115-8694-862de5699561)

**Additional context**
If it's something I did wrong, I'd appreciate your help in fixing it, as I won't be able to manually transfer over 200 old sheets to new ones.

**Comment by Veilza** [comment]
Can you try opening the settings menu, going to "World of Darkness 5e," and changing the system version field back to 4.0.0, saving, and then refreshing your world?

**Comment by f-fabner** [comment]
> Can you try opening the settings menu, going to "World of Darkness 5e," and changing the system version field back to 4.0.0, saving, and then refreshing your world?

![image](https://github.com/Rayji96/foundry-V5/assets/144628444/0127f302-5c91-42cf-8a5d-517d1133c110)

Nothing happens.

**Comment by Veilza** [comment]
Hmm. Can you try uninstalling and re-installing the WOD5E system? Or reverting back to 4.0.0 and then upgrading back to 4.0.1?

**Comment by f-fabner** [comment]
> Hmm. Can you try uninstalling and re-installing the WOD5E system?
> 
> Or reverting back to 4.0.0 and then upgrading back to 4.0.1? If you do this, make sure to back up your world and then open it while it's on 4.0.0.

I'll try this as soon as possible, and once I've made my backups...

**Comment by f-fabner** [comment]
> Hmm. Can you try uninstalling and re-installing the WOD5E system?
> 
> Or reverting back to 4.0.0 and then upgrading back to 4.0.1? If you do this, make sure to back up your world and then open it while it's on 4.0.0.

Nothing happens... Re-installing everything, change to 4.0.0, and back 4.0.1, and nothing...

**Comment by Veilza** [comment]
Update: I've made progress on something that will fix this particular issue soon. If you're still having this issue, it'll be fixed with the next release, I can promise that! However next release might still be a few days if not a week away.

**Comment by f-fabner** [comment]
> Update: I've made progress on something that will fix this particular issue soon. If you're still having this issue, it'll be fixed with the next release, I can promise that! However next release might still be a few days if not a week away.

Ok... I'm waiting, many thx and I hope everything works😁

**Comment by Veilza** [comment]
Fix being merged into dev shortly and will be fixed with the upcoming release.
