### ISSUE TITLE
[BUG] Text non readable in popout windows

### ISSUE THREAD

**Issue by ArtAmadar** [Rayji96/foundry-V5#305]
The text is black on dark in some popout wind like from the compendium. 

**To Reproduce**

1. Go to open a popout window, like compendium.
2. Text is black on dark

**Expected behavior**
A color that is readable, I'll say white our light gray following the rest of the ui.

**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/7156803/bb8566d5-2aab-4fce-955c-5916acfd8460)

**Desktop (please complete the following information):**

- FoundryVTT Version 113.5

**Additional context**
None to add

**Comment by Veilza** [comment]
This is already a known issue and should be fixed with the next release; since this is technically part of a different issue (major display overhauls/fixes), I'll close this for now to keep duplicate issues minimal.
