### ISSUE TITLE
[BUG] Power of Blood and bloodshot

### ISSUE THREAD

**Issue by Gabryel666** [Rayji96/foundry-V5#309]
**Describe the bug**
A problem with the power of blood of 9 or 10 which generates a bug on the bloodshot.

**To Reproduce**
Create a caracter and test

**Screenshots**
<img width="337" alt="image" src="https://github.com/Rayji96/foundry-V5/assets/65908230/c8a5c24a-79b3-4ff1-82f7-a3e63d31d511">

- Browser [Chrome]
<img width="254" alt="image" src="https://github.com/Rayji96/foundry-V5/assets/65908230/7636cffd-d6b3-412c-9ba8-7242d87af155">

**Thanks for this great system :)**

**Comment by Veilza** [comment]
Ah, thank you for pointing this out! It must've somehow slipped through when the localization updates were going through.

I'll get a fix out for it shortly!
