### ISSUE TITLE
[BUG] The Russian translation does not translate some elements

### ISSUE THREAD

**Issue by IHappyEndI** [Rayji96/foundry-V5#311]
**Describe the bug**
When playing in Russian, the character's sheet is not fully translated. 

**To Reproduce**
Start World

**Expected behavior**
Full translation of the sheet

**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/105805220/e09460b9-f6f6-4ac5-b8ce-1fe9a7724ec1)

**Desktop (please complete the following information):**

- Browser -  Edge
![image](https://github.com/Rayji96/foundry-V5/assets/105805220/a3bde2e2-1cff-41e5-8425-dd8824e7eed5)

**Additional context**
Thanks for the system and its regular updates ; )

**Comment by Veilza** [comment]
Strange, I can't replicate this on my end...

Can you open up the Console (by pressing F12) and see if there's any errors that show up? Anything marked in red would be an error I could look into.

**Comment by IHappyEndI** [comment]
![image](https://github.com/Rayji96/foundry-V5/assets/105805220/0c14c5ac-69a3-4a47-883b-5d1666a134fc)

There is not a single error in the console.

**Comment by Veilza** [comment]
I've been still trying to debug this, but I still can't replicate it on my end. So I'm going to suggest a couple of things:
- Try disabling all modules and seeing if the problem persists.
- Try using a different browser / opening the game in a browser (if you're just using the base FoundryVTT application right now)

If the above don't work, then I'll continue trying to think of ways to resolve this issue. However, if either of the above fixes the issue, I'd need you to give me the following information:
- Which modules are you using? Please provide a full list.
- Are you using a browser or the base FoundryVTT application? Which browser, if you're not using the base FoundryVTT application?

**Comment by Veilza** [comment]
Oh! Actually! I might have a fix for you...

Before you try the above, try uninstalling and re-installing the World of Darkness 5e system.

**Comment by IHappyEndI** [comment]
Reinstalling the system with a new world without using modules did not change the result. Nothing changes from using other browsers either (Chrome, Edge, Yandex). But it's being fixed by editing the translation lines in English ; ) .
Since the problem is local and only for me, I will close the task, especially since it can be fixed with a fairly simple crutch.

**Comment by Veilza** [comment]
So sorry about the trouble! I wish I could replicate the issue and fix this for you officially, but yes that is a workaround you can use and I'm glad you can play the game fully localized now.

If anyone else ends up experiencing the same issue, feel free to make a new issue about it or reopen this existing issue and I'll try to dig deeper into things.

**Comment by Veilza** [comment]
Hello! I actually finally found the solution for your issue here. It's an issue with the Russian localization module, as I discovered when investigating issue #321 and my solution can be found there.

**Comment by Veilza** [comment]
Hello! Just an update, I finally narrowed down the issue of what was conflicting between the Russian localization module and the WOD5E system. The latest update should be compatible with the Russian localization module: https://github.com/Rayji96/foundry-V5/releases/tag/4.4.0
