### ISSUE TITLE
[FEATURE] Increase Attribute and Disciplines custom/creation

### ISSUE THREAD

**Issue by magotusk** [Rayji96/foundry-V5#312]
I saw that you are the owner of Foundry V5 module, I have some suggestions. It would be interesting to increase the character's Attribute point limit, something similar to Roll20's V5 sheet, and allow the creation and customization of disciplines to use some homebew stuff.

**Comment by Veilza** [comment]
Thank you for the suggestions! These features are actually already planned, so I'll close this issue just to prevent the issues list from having duplicates.

**Comment by Veilza** [comment]
For posterity:

- Increasing the character's attribute point limit is part of #302
- Allowing the creationg and customization of disciplines is part of #298
