### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by f-fabner** [Rayji96/foundry-V5#324]
**Describe the bug**
I believe the humanity system is inverted; instead of losing humanity after the remorse test, the character is gaining it...

**To Reproduce**
Just keep doing the remorse test until you fail. When you fail, instead of gaining another square, you lose one... In theory, instead of having 7 humanity, you end up with 8

**Expected behavior**
The stain system is correct. Depending on the number of stains, you roll a certain number of dice... However, upon failing, you should gain another square, but instead, you're losing one... In this case, only the automatic humanity loss is inverted...

Considering that the system is... the less humanity you have, the fewer dice you roll, then either the stain system needs to be inverted, or the humanity loss system needs to be inverted...

**Screenshots**
Before roll:
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/0019595f-776d-4acf-a4a1-e981966a1248)

After roll:
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/257e9c2a-faee-462c-8e3a-f80b6bf7ccdf)

How it should be:
![image](https://github.com/Rayji96/foundry-V5/assets/144628444/10cb0617-4ebf-4769-b07f-0ef60e056fa4)

**Desktop (please complete the following information):**

- Browser [tested on edge and chrome]
- FoundryVTT Version [ 11 ]
- Foundry-V5 Version [4.2.1]

**Additional context**
Either I have been completely rolling the humanity system wrong my whole life and didn't understand it... or the system is halfway inverted. If it's my mistake, I would like to apologize and, if possible, could you explain to me how to use the character sheet in the system?

**Comment by Veilza** [comment]
The red squares are your humanity. The white squares are blank on the tracker, which I know is more than a little confusing in Dark Mode, but yes, this is intended and the sheet is working correctly.

When you have 3 humanity and 7 stains, you roll a Remorse check.
The remorse roll fails.
Your stains are cleared, and you lose a Humanity - one of the red squares turns blank to reflect this.
You're now down to 2 humanity in your second screenshot.
