### ISSUE TITLE
[BUG] Edges and Perks issue

### ISSUE THREAD

**Issue by Alemdion** [Rayji96/foundry-V5#328]
Edges and Perks cannot be edited/removed

1. Go to 'Edges'
2. Click on 'Add Edge' and select any option
3. Click on 'Add Perk'
4. Click on 'Edit' and rename Perk
5. Newly added perk disappears, and Edge cannot be removed

Expected that the Edges and Perks can be edited and removed correctly

![image](https://github.com/Rayji96/foundry-V5/assets/14318449/1b6c80df-0db4-47f8-a26a-5c3bb688d339)

- Chrome Version 125.0.6422.77
- FoundryVTT Version 12, build 324
- Foundry-V5 Version 4.3.0

**Comment by Veilza** [comment]
Found the issue and managed to get it fixed quickly--turns out it's halfway due to an issue from the transition to V12, halfway due to the old way powers used to be managed. I should be able to get a new release out relatively quickly!

Thanks for reporting this!
