### ISSUE TITLE
New Sheet Layout

### ISSUE THREAD

**Issue by lipefl** [Rayji96/foundry-V5#33]
I'm about to start a new campaign and to put players in the mood, i made this with css to resemble more the sheet from the book (the font from the book has an open license).
I was thinking about publishing as a css only module. But i decided to show you first, maybe you want to add as an option inside the system. What do you think?

![](https://i.imgur.com/ThPPoyW.png)

**Comment by Rayji96** [comment]
That looks incredible! Can you make a pull request or something? I'd love to make that the default look. Unfortunately my experience is as a back end dev and not front end so this is definitely not my expertise haha :)

**Comment by lipefl** [comment]
Sure, i'll send as separate files, so you can decide the best way to "merge" them.
You already did a great job with the system :D

**Comment by Rayji96** [comment]
Sure I can handle merging the css :). You can attach files onto github comments iirc.

**Comment by lipefl** [comment]
I did it earlier today, but i forgot to "pull request", sorry.
