### ISSUE TITLE
Improvements for NPC Sheets - Spirits - BlackSpiralDancer - Fomori

### ISSUE THREAD

**Issue by Creos945** [Rayji96/foundry-V5#336]
Would it be possible to have NPC sheets suitable for dedicated options for spirits, a simplified NPC sheet to generate BSDs that takes gifts and rage into account, and an NPC sheet suitable for Fomori? 

Currently, the generated NPCs only take into account the statistics for creating humans and ghouls. An NPC sheet for generating vampires is also needed.

Grazie mille 
Creos

**Comment by Veilza** [comment]
This is already planned in the works! Worry not, it's going to be gotten to sooner or later.
