### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by FederSchakal** [Rayji96/foundry-V5#337]
Hello,
I didn't want to report a mistake, just a correction of the names from the German rules.

The following names are different in the hunter core rulebook:
- “Artillerie” as “Sprengstoff” 
- "Globaler Zugang" as "Globaler Zugriff"
- "Das Ünnatürliche verhindern" as "Übernatürliches vereiteln"
- "Das Unnatürliche abwehren" as "Übernatürliches zurücktreiben"
- "Das Unnatürliche spüren" as "Übernatürliches spüren"

Thank you for your work. Keep it up!

**Comment by Veilza** [comment]
Thank you for the translation corrections! They're greatly appreciated and I'll make sure they get pushed out in the next update.
