### ISSUE TITLE
[ENHANCEMENT] Additional Images for Werewolf Forms

### ISSUE THREAD

**Issue by Creos945** [Rayji96/foundry-V5#339]
Would it be possible to have uploaded 3 images in the character sheet for the player characters of Werewolf? One for the Homid form, one for the Crinos form, and one for the Lupus form?

**Comment by Veilza** [comment]
It's in the works! There's going to be a whole upgrade of the Werewolf forms at one point or another, but it's been a little slow going. Definitely planned, though!
