### ISSUE TITLE
[TRANSLATE] Small additions to the Russian translation

### ISSUE THREAD

**Issue by IHappyEndI** [Rayji96/foundry-V5#340]
Good afternoon
Added a translation to some untranslated lines in the Russian translation. Could you please add it to the system?

[core-ru.json](https://github.com/user-attachments/files/15896022/core-ru.json)
[vampire-ru.json](https://github.com/user-attachments/files/15896023/vampire-ru.json)

**Comment by Veilza** [comment]
Ah, one comment I do have: I see you translated "MacroNote" as "Заметки макроса", which I don't think is right. The "Macro Note" key is actually a sentence - "If a macro is listed, then it will execute directly after the item is clicked or the roll is made."

If you'd like to provide an updated translation for that, you can just post it here in a comment and I can fix that.

**Comment by IHappyEndI** [comment]
Oh, I see this mistake. I am sending the corrected file
[core-ru.json](https://github.com/user-attachments/files/15896251/core-ru.json)

**Comment by IHappyEndI** [comment]
And could you tell me. Is it possible at the moment to translate these elements (underlined in green) without getting into the code?
![Sellect roll](https://github.com/Rayji96/foundry-V5/assets/105805220/63ee4623-bd00-46c2-8a87-b6bb9e606b54)
![Total](https://github.com/Rayji96/foundry-V5/assets/105805220/2b1fb58b-97fa-4a04-b485-c72103a9d792)

**Comment by Veilza** [comment]
Oh, yes! Could you give me the translations for what "Select Roll" and "Total" should be? I can quickly add those as well.

**Comment by IHappyEndI** [comment]
If you adapt this to where they are used, you will get:
Select Roll: "Сформируйте проверку" 
Total: "Результат"

**Comment by Veilza** [comment]
Thank you! I've updated the development build with these new localizations. It should be included with the next release.
