### ISSUE TITLE
[BUG] Limited Permission users can still view sheet data

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#38]
**Describe the bug**
Users with limited permissions can still view character sheets. Should only be Observer and above that can do that.

**To Reproduce**
1. Set a sheet to Limited permissions to a user
2. Login to said user
3. Find the Limited permissions sheet
4. Open the sheet

**Expected behavior**
The user should be able to see the character in the actors list but not view any info on the sheet (perhaps just a blank sheet for now).

**Desktop (please complete the following information):**
 - Browser: FoundryVTT chromium viewer
 - FoundryVTT Version: 0.7.9
 - Foundry-V5 Version: 1.2.1

**Additional context**
DnD5e system just shows a blank sheet with name and image. Could probably just hide everything but name and image as well.

**Comment by pedroboh** [comment]
So, I'm a complete noob but I've been comparing the files on how the dnd5e implements their sheets and how you do it and it seems like you gotta have a different template for the limited sheet and on the actor you check the permission level before pulling the correct template.

I believe this is the relevant bit from the base.js(I think it's the equivalent to your actor-sheet.js) file in the dnd5e implementation

[get limited sheet.txt](https://github.com/Rayji96/foundry-V5/files/6407279/get.limited.sheet.txt)

but there's also a couple more references to limited just after that in the base.js, don't know how relevant they are

[base.txt](https://github.com/Rayji96/foundry-V5/files/6407315/base.txt)

and their limited sheet is quite short it's just

[dnd limited sheet.txt](https://github.com/Rayji96/foundry-V5/files/6407277/dnd.limited.sheet.txt)

I'm more of a python guy, so these are just some guesses from comparing things, but maybe it helps a bit

**Comment by pedroboh** [comment]
Ok, I managed to do it

[actor-sheet.txt](https://github.com/Rayji96/foundry-V5/files/6408213/actor-sheet.txt)
[limited-sheet.txt](https://github.com/Rayji96/foundry-V5/files/6408214/limited-sheet.txt)

if I figure out how to do pull requests later I'll do it
