### ISSUE TITLE
[BUG]Blood Surge dice to add shows one higher than it should 

### ISSUE THREAD

**Issue by tkightly** [Rayji96/foundry-V5#45]
**Describe the bug**
For all levels of blood potency, the Blood Surge value shows one higher.

For Blood Potency 0, the Blood Surge value shows to add 1 extra dice. Pg 216 of the core rulebook shows it should be 0
For Blood Potency 1-2, the Blood Surge value shows to add 2 extra dice. Pg 216 of the core rulebook shows it should be 1
and so on...

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to an actor's character sheet
2. Click on the Blood Tab
3. For any given Blood Potency value, compare the Blood Surge value against Pg 216 of the core rulebook

**Expected behaviour**
For any given Blood Potency value, the Blood Surge value should match Pg 216 of the core rulebook

**Screenshots**
<img width="401" alt="Screenshot 2021-02-12 at 16 00 50" src="https://user-images.githubusercontent.com/40869890/107791345-bc0ee680-6d4b-11eb-8853-1b0e5a3c57d4.png">
<img width="395" alt="Screenshot 2021-02-12 at 16 00 56" src="https://user-images.githubusercontent.com/40869890/107791347-bca77d00-6d4b-11eb-815b-dbfa8e6787a5.png">

**Desktop (please complete the following information):**

- Browser [Built-in foundry, or Chrome/New Edge]
- FoundryVTT Version [0.7.9]
- Foundry-V5 Version [1.3.0 or 1.2.1]

**Comment by Rayji96** [comment]
They actually upped all the blood surge values in the latest errata that came with the free companion book :)

**Comment by tkightly** [comment]
Hi Ray, thanks for pointing me to the errata in the companion book. I had of course seen the Sep 2019 errata but was not aware of this one! I will close the issue :)
