### ISSUE TITLE
[FEATURE] Show Power desc in chat message

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#50]
**Is your feature request related to a problem? Please describe.**
Would be nice to see power desc in outputted roll

**Describe the solution you'd like**
Expandable spoiler text in power chat output that shows desc

**Describe alternatives you've considered**
Or just not show it or show it all the time (thought power desc could be outrageously long lol)

**Comment by eisenfuchs** [comment]
I would like to see this work, but a spoiler is definitely required. either than or a way to just have a shortened text per default. What I also would like to see, is adding the IMAGE of the power in chat, since I spent a lot of time adding graphics to powers.
