### ISSUE TITLE
[BUG] Power Rolls don't consider Blood Potency

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#55]
**Describe the bug**
Power rolls should include bonus from blood potency rather than rely on user to add it in mod.

**Acceptance Criteria**
Blood Potency bonus automatically added to power rolls.

**Comment by eisenfuchs** [comment]
I'm sadly having trouble fixing this, and I don't know why. I've added a third dice component for the power roll, but I can't seem to make it work. How do I get the blood_potency of the actor? I've tried this.actor.data.data.blood_potency.value, but that's not working bc bp is an array, right? I couldn't find out where the value is.

**Comment by MarkusOzgur** [comment]
I had fixed it for me locally with this very simple code, might wanna implent this version till a "cleaner" one is made:

>   _onVampireRoll(event) {
>     event.preventDefault()
>     const element = event.currentTarget
>     const dataset = element.dataset
>     const item = this.actor.items.get(dataset.id)
>     let disciplineValue = 0
>     if (item.data.data.discipline === 'rituals') {
>       disciplineValue = this.actor.data.data.disciplines.sorcery.value
>     } else if (item.data.data.discipline === 'ceremonies') {
>       disciplineValue = this.actor.data.data.disciplines.oblivion.value
>     } else {
>       disciplineValue = this.actor.data.data.disciplines[item.data.data.discipline].value
>     }
> 
>     const dice1 = item.data.data.dice1 === 'discipline' ? disciplineValue : this.actor.data.data.abilities[item.data.data.dice1].value
> 
>     let dice2
>     if (item.data.data.dice2 === 'discipline') {
>       dice2 = disciplineValue
>     } else if (item.data.data.skill) {
>       dice2 = this.actor.data.data.skills[item.data.data.dice2].value
>     } else {
>       dice2 = this.actor.data.data.abilities[item.data.data.dice2].value
>     }
> 
**>     let potency = this.actor.data.data.blood.potency
>     let discPower
>     switch (potency) {
>       case 0:
>       case 1:
>         discPower = 0
>         break;
>       case 2:
>       case 3:
>         discPower = 1
>         break;
>       case 4:
>       case 5:
>         discPower = 2
>         break;
>       case 6:
>       case 7:
>         discPower = 3
>         break;
>       case 8:
>       case 9:
>         discPower = 4
>         break;
>       case 10:
>         discPower = 5
>         brea**k;
>     }
> 
>     const dicePool = dice1 + dice2 **+ discPower**
>     this._rollDice(dicePool, this.actor, `${item.data.name}`)
>   }

**Comment by MarkusOzgur** [comment]
I had fixed it for me locally with a very simple addition, hope it helps!
(the method is in the actor-sheet.js file)

```
  _onVampireRoll(event) {
    event.preventDefault()
    const element = event.currentTarget
    const dataset = element.dataset
    const item = this.actor.items.get(dataset.id)
    let disciplineValue = 0
    if (item.data.data.discipline === 'rituals') {
      disciplineValue = this.actor.data.data.disciplines.sorcery.value
    } else if (item.data.data.discipline === 'ceremonies') {
      disciplineValue = this.actor.data.data.disciplines.oblivion.value
    } else {
      disciplineValue = this.actor.data.data.disciplines[item.data.data.discipline].value
    }

    const dice1 = item.data.data.dice1 === 'discipline' ? disciplineValue : this.actor.data.data.abilities[item.data.data.dice1].value

    let dice2
    if (item.data.data.dice2 === 'discipline') {
      dice2 = disciplineValue
    } else if (item.data.data.skill) {
      dice2 = this.actor.data.data.skills[item.data.data.dice2].value
    } else {
      dice2 = this.actor.data.data.abilities[item.data.data.dice2].value
    }

    let potency = this.actor.data.data.blood.potency
    let discPower
    switch (potency) {
      case 0:
      case 1:
        discPower = 0
        break;
      case 2:
      case 3:
        discPower = 1
        break;
      case 4:
      case 5:
        discPower = 2
        break;
      case 6:
      case 7:
        discPower = 3
        break;
      case 8:
      case 9:
        discPower = 4
        break;
      case 10:
        discPower = 5
        break;
    }

    const dicePool = dice1 + dice2 + discPower
    this._rollDice(dicePool, this.actor, `${item.data.name}`)
  }
```
