### ISSUE TITLE
[BUG] Use Hunger Dice for Rouse

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#56]
**Describe the bug**
Rouse checks should use hunger dice instead of regular dice because Oblivion has extra effects on bestial fail.

**Acceptance Criteria**
Roll hunger dice when clicking Rouse Roll.

**Comment by eisenfuchs** [comment]
I fixed this on my fork, but it's not a clean solution and requires refactoring (it currently is a duplication of the onRoll event).

Let me know if you still want me to pull it.

![image](https://user-images.githubusercontent.com/79832708/110211842-b7e06f80-7e98-11eb-96b9-add78b7dcf3a.png)

**Comment by bmgraves** [comment]
I was actually just looking at this yesterday. I was thinking about combining onRoll and onVampireRoll, with some logic to handle the different use case scenario's. I'll take a look at that now and see how feasible that is.
