### ISSUE TITLE
[FEATURE] Implement compendium with rules references.

### ISSUE THREAD

**Issue by bmgraves** [Rayji96/foundry-V5#58]
**Is your feature request related to a problem? Please describe.**
This is something i'm currently working on. I've reached out to WW/Paradox licensing with an outline of what this would be and I'm waiting for a response. They may say no. But I wanted to mark this down and get feedback in the meantime.

What I propose is creating a compendium/Built in references to rules, WITHOUT the rules themselves, but rather page numbers the rules can be found on. Additionally part of this would be implementing a method VIA the pdfFoundy module, for storytellers to upload their own copy's of a rulebook, which would be linked to via the page numbers. So IF a storyteller owned the PDF and uploaded it, they players would be able to click links to certain rules and have them pulled up in the PDF directly to the correct page number.

again, this all hinges on paradox confirming that this wouldn't be violating their licensing, but it may be a decent way to really expanding the system to make looking up things like merits/disciplines/other rules easier.

**Comment by eisenfuchs** [comment]
I guess the only thing we can hope for is a paid premium module that allows them to get money for it. Similar things are done by DSA (the dark eye), Forbidden Lands, Alien and Warhammer Fantasy.

**Comment by greelgorke** [comment]
Just some hints, you may or may not be aware of those:
there is a possibility for non-comercial licensing: https://www.worldofdarkness.com/dark-pack
an example of such found here https://www.reddit.com/r/WhiteWolfRPG/comments/auljet/v5_character_creation_quick_reference/ is this document: https://drive.google.com/file/d/1-B1Ldd5FIND5Gm299BrcqP-Q-lNK6MnQ/view

This looks pretty much like the proposed compendium right?

**Comment by eisenfuchs** [comment]
Oh, I didn't see the reply!

that would be cool. but also, I volunteer to add images from games icons net to all the discipline powers. I did so for my game as well, and they work really well.
