### ISSUE TITLE
[FEATURE] Powers should Track discipline level, and Rouse check requirements

### ISSUE THREAD

**Issue by bmgraves** [Rayji96/foundry-V5#61]
**Is your feature request related to a problem? Please describe.**
Not all powers require rouse checks, some require multiple rouse checks, and depending on blood potency different powers of different levels may have rouse checks that are eligible for re-roll

**Describe the solution you'd like**
At its simplest level Discipline powers should have a "level" field and a "# of Rouse checks required" field that present this information.

 As a further enhancement we could add a "rouse" button to any power that requires a rouse check that will take into account the number of checks required, as well as whether or not they can be re-rolled.

**Comment by Rayji96** [comment]
Discipline level would be a good field to show but how necessary is a # of Rouse checks vs having it in the power desc and expanding it in the table?

**Comment by zifre** [comment]
I see a pull request in pending that implements this feature, do you know when this will be merged? My group is about to start a V5 campaign and I would love to have these quality of life features available by then.

**Comment by Rayji96** [comment]
Mid February? You likely won't get it until I make a release. I'm on vacation right now but I have a release planned for mid Feb when I'm back at my PC. I like to do a bug scrub before every release just to be sure. :)

**Comment by Rayji96** [comment]
I think all rouse check required powers are single rouse checks? I could be wrong. The most recent update added discipline levels. Going to close this until further info :)

**Comment by gbursson** [comment]
Rouse check icon next do Power __is__ taking Blood Potency into account.
It rerolls a Rouse check (essentially rolls two dice)

What would be nice, is to have a field to enter # of Rouse checks required for Powers that have more than one needed.
It is QoL feature, and an edge case (for maybe 4 Powers altogether)
