### ISSUE TITLE
[FEATURE] Specialties as a dropdown menu when rolling, and also have a visual indicator on related skills in PC sheet

### ISSUE THREAD

**Issue by scomick** [Rayji96/foundry-V5#65]
1- When rolling a test, would be great if, in the roll window, you could have a dropdown menu that lets a user select a specialty related to their roll (which would then automatically contribute an extra die). 

![image](https://user-images.githubusercontent.com/79115220/111070112-7ce8c800-84a6-11eb-9771-01e42069d3b0.png)

2- A visual indicator next to a skill on the PC sheet when it has a specialty, to avoid having users needing to scroll down to the bottom of the sheet every time to double check which specialties they have. The official V5 character sheet has specialties listed next to the skill, but since we don't have room here I'm thinking maybe a different colored font for the skill or maybe a checkbox? Something automated, tied to the "skill" field of the specialty, would be great

![image](https://user-images.githubusercontent.com/79115220/111070081-6b9fbb80-84a6-11eb-8ab1-beccada09bc2.png)

**Comment by Rayji96** [comment]
Specialties are now rollable by clicking the icon in the specialty table. It'll automatically apply the +1 and use whatever skill is tied to the specialty. Does that cover this use case?

**Comment by scomick** [comment]
I think it's alright for covering the additional die to the roll thing, but I still think some sort of visual indicator next to the relevant skill to remind a player that they have a specialty would be good. Just because the last few games we played, two of my players kept forgetting to scroll down on their sheet to check their specialties and there were a few missed rolls as a result. 

If a visual indicator isn't possible, perhaps a manual checkbox of sorts next to each skill (maybe named "Specialty?") that a player could at least "check" during PC creation so they have a way to quickly notice during gameplay "Oh yes, I have a specialty/specialties here... let me scroll down and double check what that/those may be"

**Comment by Rayji96** [comment]
I feel like that's a "knowing your kit" issue but I'll see what I can do. I'll likely add an asterisk next to skills as a checkbox might clutter up and already cluttered sheet

**Comment by scomick** [comment]
Yeah, a simple visual cue as small as an asterisk should be enough. And yeah this is problem with players who are used to the official sheets where your specialties are listed right nxt to your skills for sure, but even I as a GM don't remember to scroll down when i'm checking their sheets to help them so it'd definitely be a great little addition

**Comment by Rayji96** [comment]
An asterisk with a tooltip on hover listing your specialties shouldn't be too hard. I'd have to consolidate the item list that is the specialties list some how though.
