### ISSUE TITLE
[FEATURE] Conditions on Actor Sheets

### ISSUE THREAD

**Issue by eisenfuchs** [Rayji96/foundry-V5#71]
There are some abilities in V5 that work like buffs. For example using Host Spirit (adds 2 dice to Physical dice pools and +2 Health) or being a Werewolf in Crinos form (adds 3 dice to Physical dice pools, and probably also +3 to Health). Currently I only know of these as examples, but Horrid Form even allows specific physical traits to be raised.

The idea would be that when you add a "Buff" (or Form), your sheet goes into Buff Setup Mode (all dots vanish) and you can add new dots (preferably in a different color than usual to show they are temporary). When Buff Setup is done, the Buff becomes a toggle that can be activated to add the bonus dice/health boxes to the sheet/rolls. 

Currently, I'm using duplicated character sheets for this. The problem is keeping them up to date becomes an impossible thing, over time.

I don't consider this to be high priority. It's just a nice-to have thing that probably adds some issues, but it would maybe help make Werewolves playable too, because currently, I'm having 3 sheets for them.

**Comment by Rayji96** [comment]
It would be good to track buffs like effects in DnD. Could be as simple as a list of buffs under specialties or something.

**Comment by Veilza** [comment]
Slightly stealing this issue to encapsulate not only the original intent--an area for "buffs" on the sheets--but also extend it to have a place for conditions in general on the actor sheets.
