### ISSUE TITLE
[FEATURE] Minimize NOTES section in "Other" tab on PC Sheet

### ISSUE THREAD

**Issue by scomick** [Rayji96/foundry-V5#72]
In the "Other" tab on a PC sheet, the Equipment section sees more use/reference by my players than the new NOTES section that appeared in the latest update. 
I'd like a way to either flip those sections so NOTES ends up at the bottom, or a way to minimize the NOTES section because right now it creates a lot of blank space/scrolling every time when my characters need to update/edit their equipment.

![image](https://user-images.githubusercontent.com/79115220/112765200-084f7680-8fda-11eb-8f95-99f85b097a70.png)

**Comment by NbrouetEuronews** [comment]
Maybe two columns would be nice : one "equipement", one "notes"
